import XCTest
@testable import Swiftcamp

/// The catalog against the sprite sheet it was generated beside.
///
/// A symbol naming an image the sheet lacks is not an error MapLibre
/// reports once; it logs on every frame. This is the check that keeps the
/// two files, both generated by `scripts/make_shields.py`, from drifting
/// if one is regenerated and the other committed stale.
final class SymbolCatalogTests: XCTestCase {
    private func spriteIndex(_ name: String) throws -> Set<String> {
        // Hosted by the app, so its bundle is the one the map reads.
        let url = try XCTUnwrap(Bundle.main.url(forResource: name, withExtension: "json", subdirectory: "sprites"),
                                "\(name).json is in the bundle")
        let index = try XCTUnwrap(JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any])
        return Set(index.keys)
    }

    func testEveryImageIsInBothSpriteSheets() throws {
        let one = try spriteIndex("sprite")
        let two = try spriteIndex("sprite@2x")
        for entry in SymbolCatalog.entries + [SymbolCatalog.search] {
            XCTAssertTrue(one.contains(entry.image), "\(entry.image) at 1x")
            XCTAssertTrue(two.contains(entry.image), "\(entry.image) at 2x")
        }
    }

    func testNamesAreUniqueAndGrouped() {
        let names = SymbolCatalog.entries.map(\.name)
        XCTAssertEqual(Set(names).count, names.count)
        XCTAssertEqual(Set(SymbolCatalog.entries.map(\.group)), Set(SymbolCatalog.groups))
        for entry in SymbolCatalog.entries {
            XCTAssertTrue(["bottom", "center"].contains(entry.anchor), entry.name)
        }
    }

    /// Garmin's names, as devices and BaseCamp write them, resolve to their
    /// own artwork; anything else draws as the generic marker without
    /// being claimed as known.
    func testLookupIsByGarminNameIgnoringCase() {
        XCTAssertEqual(SymbolCatalog.entry(for: "Flag, Blue").image, "symbol-flag-blue")
        XCTAssertEqual(SymbolCatalog.entry(for: "flag, blue").image, "symbol-flag-blue")
        XCTAssertEqual(SymbolCatalog.entry(for: "Gas Station").image, "symbol-gas-station")

        XCTAssertEqual(SymbolCatalog.entry(for: nil), SymbolCatalog.fallback)
        XCTAssertEqual(SymbolCatalog.entry(for: "Zoo"), SymbolCatalog.fallback)
        XCTAssertNil(SymbolCatalog.known(nil))
        XCTAssertNil(SymbolCatalog.known("Zoo"))
        XCTAssertNotNil(SymbolCatalog.known("Summit"))
    }

    func testAPinStandsOnItsTipAndABlockSitsOnThePlace() {
        XCTAssertEqual(SymbolCatalog.entry(for: "Pin, Red").anchor, "bottom")
        XCTAssertEqual(SymbolCatalog.entry(for: "Flag, Red").anchor, "bottom")
        XCTAssertEqual(SymbolCatalog.entry(for: "Block, Red").anchor, "center")
        XCTAssertEqual(SymbolCatalog.entry(for: "Circle with X").anchor, "center")
        XCTAssertEqual(SymbolCatalog.search.anchor, "bottom")
    }
}
