// Generated by scripts/make_shields.py — do not edit by hand.
//
// Regenerate after changing shield artwork:
//     python3 scripts/make_shields.py

enum ShieldCatalog {
    /// State codes with an entry in the sprite sheet. A code outside this
    /// list falls back to the generic plate; the style matches against it
    /// rather than building an image name blind, because MapLibre answers a
    /// missing image by logging every frame rather than failing once.
    static let states: [String] = ["al", "ak", "az", "ar", "ca", "co", "ct", "de", "dc", "fl", "ga", "hi", "id", "il", "in", "ia", "ks", "ky", "la", "me", "md", "ma", "mi", "mn", "ms", "mo", "mt", "ne", "nv", "nh", "nj", "nm", "ny", "nc", "nd", "oh", "ok", "or", "pa", "ri", "sc", "sd", "tn", "tx", "ut", "vt", "va", "wa", "wv", "wi", "wy"]

    /// Numeral colour per shield, taken from openstreetmap-americana's own
    /// definitions. Not derivable from the artwork: Idaho's plate is black,
    /// Minnesota's is blue, California's spade is green, and each needs
    /// white numerals that a light-background shield must not use.
    static let textColors: [String: String] = [
        "shield-ak": "#1d1d1d",
        "shield-al": "#1d1d1d",
        "shield-ar": "#1d1d1d",
        "shield-az": "#1d1d1d",
        "shield-ca": "#ffffff",
        "shield-co": "#1d1d1d",
        "shield-ct": "#1d1d1d",
        "shield-dc": "#1d1d1d",
        "shield-de": "#1d1d1d",
        "shield-fl": "#1d1d1d",
        "shield-ga": "#1d1d1d",
        "shield-hi": "#1d1d1d",
        "shield-ia": "#1d1d1d",
        "shield-id": "#ffffff",
        "shield-il": "#1d1d1d",
        "shield-in": "#1d1d1d",
        "shield-interstate": "#ffffff",
        "shield-ks": "#1d1d1d",
        "shield-ky": "#1d1d1d",
        "shield-la": "#1d1d1d",
        "shield-ma": "#1d1d1d",
        "shield-md": "#1d1d1d",
        "shield-me": "#1d1d1d",
        "shield-mi": "#1d1d1d",
        "shield-mn": "#ffffff",
        "shield-mo": "#1d1d1d",
        "shield-ms": "#1d1d1d",
        "shield-mt": "#1d1d1d",
        "shield-nc": "#1d1d1d",
        "shield-nd": "#1d1d1d",
        "shield-ne": "#1d1d1d",
        "shield-nh": "#1d1d1d",
        "shield-nj": "#1d1d1d",
        "shield-nm": "#1d1d1d",
        "shield-nv": "#1d1d1d",
        "shield-ny": "#1d1d1d",
        "shield-oh": "#1d1d1d",
        "shield-ok": "#1d1d1d",
        "shield-or": "#1d1d1d",
        "shield-pa": "#1d1d1d",
        "shield-plate": "#1d1d1d",
        "shield-ri": "#1d1d1d",
        "shield-sc": "#003f87",
        "shield-sd": "#1d1d1d",
        "shield-tn": "#1d1d1d",
        "shield-tx": "#1d1d1d",
        "shield-us": "#1d1d1d",
        "shield-ut": "#1d1d1d",
        "shield-va": "#1d1d1d",
        "shield-vt": "#006b3f",
        "shield-wa": "#1d1d1d",
        "shield-wi": "#1d1d1d",
        "shield-wv": "#1d1d1d",
        "shield-wy": "#1d1d1d",
    ]
}
