// Generated by scripts/make_shields.py from scripts/make_symbols.py.
// Do not edit by hand.

/// The waypoint symbols the app can draw, by Garmin's names.
///
/// Generated beside the sprite sheet so an image name here cannot name an
/// image that is not there: MapLibre answers a missing image by logging
/// every frame rather than failing once. A symbol outside this list is kept
/// on the waypoint and exported untouched; it draws as the generic marker.
enum SymbolCatalog {
    struct Entry: Hashable, Sendable {
        /// Garmin's name, as `<sym>` carries it.
        let name: String
        /// The sprite image.
        let image: String
        /// Where the image sits on the place: `bottom` for a pin's tip or a
        /// flag's foot, `center` for a shape that sits on the spot.
        let anchor: String
        /// The menu section.
        let group: String
    }

    /// In menu order.
    static let entries: [Entry] = [
        Entry(name: "Waypoint", image: "symbol-waypoint", anchor: "bottom", group: "Markers"),
        Entry(name: "Flag, Blue", image: "symbol-flag-blue", anchor: "bottom", group: "Markers"),
        Entry(name: "Flag, Green", image: "symbol-flag-green", anchor: "bottom", group: "Markers"),
        Entry(name: "Flag, Red", image: "symbol-flag-red", anchor: "bottom", group: "Markers"),
        Entry(name: "Pin, Blue", image: "symbol-pin-blue", anchor: "bottom", group: "Markers"),
        Entry(name: "Pin, Green", image: "symbol-pin-green", anchor: "bottom", group: "Markers"),
        Entry(name: "Pin, Red", image: "symbol-pin-red", anchor: "bottom", group: "Markers"),
        Entry(name: "Block, Blue", image: "symbol-block-blue", anchor: "center", group: "Markers"),
        Entry(name: "Block, Green", image: "symbol-block-green", anchor: "center", group: "Markers"),
        Entry(name: "Block, Red", image: "symbol-block-red", anchor: "center", group: "Markers"),
        Entry(name: "Diamond, Blue", image: "symbol-diamond-blue", anchor: "center", group: "Markers"),
        Entry(name: "Diamond, Green", image: "symbol-diamond-green", anchor: "center", group: "Markers"),
        Entry(name: "Diamond, Red", image: "symbol-diamond-red", anchor: "center", group: "Markers"),
        Entry(name: "Circle with X", image: "symbol-circle-with-x", anchor: "center", group: "Markers"),
        Entry(name: "Gas Station", image: "symbol-gas-station", anchor: "bottom", group: "Services"),
        Entry(name: "Lodging", image: "symbol-lodging", anchor: "bottom", group: "Services"),
        Entry(name: "Restaurant", image: "symbol-restaurant", anchor: "bottom", group: "Services"),
        Entry(name: "Bar", image: "symbol-bar", anchor: "bottom", group: "Services"),
        Entry(name: "Shopping Center", image: "symbol-shopping-center", anchor: "bottom", group: "Services"),
        Entry(name: "Parking Area", image: "symbol-parking-area", anchor: "bottom", group: "Services"),
        Entry(name: "Restroom", image: "symbol-restroom", anchor: "bottom", group: "Services"),
        Entry(name: "Information", image: "symbol-information", anchor: "bottom", group: "Services"),
        Entry(name: "Post Office", image: "symbol-post-office", anchor: "bottom", group: "Services"),
        Entry(name: "Medical Facility", image: "symbol-medical-facility", anchor: "bottom", group: "Services"),
        Entry(name: "Police Station", image: "symbol-police-station", anchor: "bottom", group: "Services"),
        Entry(name: "Residence", image: "symbol-residence", anchor: "bottom", group: "Services"),
        Entry(name: "Museum", image: "symbol-museum", anchor: "bottom", group: "Services"),
        Entry(name: "Airport", image: "symbol-airport", anchor: "bottom", group: "Services"),
        Entry(name: "Ferry", image: "symbol-ferry", anchor: "bottom", group: "Services"),
        Entry(name: "Campground", image: "symbol-campground", anchor: "bottom", group: "Outdoors"),
        Entry(name: "Picnic Area", image: "symbol-picnic-area", anchor: "bottom", group: "Outdoors"),
        Entry(name: "Park", image: "symbol-park", anchor: "bottom", group: "Outdoors"),
        Entry(name: "Scenic Area", image: "symbol-scenic-area", anchor: "bottom", group: "Outdoors"),
        Entry(name: "Summit", image: "symbol-summit", anchor: "bottom", group: "Outdoors"),
        Entry(name: "Swimming Area", image: "symbol-swimming-area", anchor: "bottom", group: "Outdoors"),
        Entry(name: "Bike Trail", image: "symbol-bike-trail", anchor: "bottom", group: "Outdoors"),
        Entry(name: "Danger Area", image: "symbol-danger-area", anchor: "bottom", group: "Outdoors"),
    ]

    /// The menu sections, in order.
    static let groups: [String] = ["Markers", "Services", "Outdoors"]

    /// What draws when a waypoint has no symbol, or one without artwork.
    static let fallback = entries[0]

    /// Where a search result is drawn until it is saved or dismissed.
    static let search = Entry(name: "", image: "symbol-search", anchor: "bottom", group: "")

    /// The entry for a stored symbol name, or nil for none or one without
    /// artwork. Case-insensitive because the names travel through files
    /// other software wrote.
    static func known(_ symbol: String?) -> Entry? {
        symbol.flatMap { byName[$0.lowercased()] }
    }

    /// The entry to draw a stored symbol name with: its own, or the fallback.
    static func entry(for symbol: String?) -> Entry {
        known(symbol) ?? fallback
    }

    private static let byName: [String: Entry] =
        Dictionary(uniqueKeysWithValues: entries.map { ($0.name.lowercased(), $0) })
}
