import Foundation

/// Garmin's MapSource symbol numbers, as a GDB file stores a waypoint's
/// icon, to the names the same symbols carry in GPX. Both are Garmin's
/// vocabulary; the pairing is the one MapSource and BaseCamp use when
/// they write GPX, and it is what lets a waypoint keep its flag across
/// the migration. A number outside the table is a symbol newer than the
/// table, and reads as the generic waypoint rather than as nothing.
///
/// Numbers 500 to 563 are the user's custom symbols, which BaseCamp
/// writes to GPX as "Custom 0" through "Custom 63".
enum GDBSymbols {
    static func name(for number: Int) -> String {
        if (500...563).contains(number) { return "Custom \(number - 500)" }
        return table[number] ?? "Waypoint"
    }

    /// GPX name to MapSource number, for writing. Nil for a name the table
    /// lacks; the writer then uses the generic waypoint's number.
    static func number(for name: String) -> Int? {
        if name.hasPrefix("Custom "), let n = Int(name.dropFirst(7)), (0...63).contains(n) { return 500 + n }
        return byName[name.lowercased()]
    }

    private static let byName: [String: Int] = Dictionary(table.map { ($1.lowercased(), $0) }, uniquingKeysWith: { a, _ in a })

    private static let table: [Int: String] = [
        0: "Anchor",
        1: "Bell",
        2: "Diamond, Green",
        3: "Diamond, Red",
        4: "Diver Down Flag 1",
        5: "Diver Down Flag 2",
        6: "Bank",
        7: "Fishing Area",
        8: "Gas Station",
        9: "Horn",
        10: "Residence",
        11: "Restaurant",
        12: "Light",
        13: "Bar",
        14: "Skull and Crossbones",
        15: "Square, Green",
        16: "Square, Red",
        17: "Buoy, White",
        18: "Waypoint",
        19: "Shipwreck",
        20: "Man Overboard",
        21: "Navaid, Amber",
        22: "Navaid, Black",
        23: "Navaid, Blue",
        24: "Navaid, Green",
        25: "Navaid, Green/Red",
        26: "Navaid, Green/White",
        27: "Navaid, Orange",
        28: "Navaid, Red",
        29: "Navaid, Red/Green",
        30: "Navaid, Red/White",
        31: "Navaid, Violet",
        32: "Navaid, White",
        33: "Navaid, White/Green",
        34: "Navaid, White/Red",
        35: "Dot, White",
        36: "Radio Beacon",
        37: "Boat Ramp",
        38: "Campground",
        39: "Restroom",
        40: "Shower",
        41: "Drinking Water",
        42: "Telephone",
        43: "Medical Facility",
        44: "Information",
        45: "Parking Area",
        46: "Park",
        47: "Picnic Area",
        48: "Scenic Area",
        49: "Skiing Area",
        50: "Swimming Area",
        51: "Dam",
        52: "Controlled Area",
        53: "Danger Area",
        54: "Restricted Area",
        55: "Ball Park",
        56: "Car",
        57: "Hunting Area",
        58: "Shopping Center",
        59: "Lodging",
        60: "Mine",
        61: "Trail Head",
        62: "Truck Stop",
        63: "Exit",
        64: "Flag",
        65: "Circle with X",
        66: "Mile Marker",
        67: "TracBack Point",
        68: "Golf Course",
        69: "City (Small)",
        70: "City (Medium)",
        71: "City (Large)",
        72: "City (Capitol)",
        73: "Amusement Park",
        74: "Bowling",
        75: "Car Rental",
        76: "Car Repair",
        77: "Fast Food",
        78: "Fitness Center",
        79: "Movie Theater",
        80: "Museum",
        81: "Pharmacy",
        82: "Pizza",
        83: "Post Office",
        84: "RV Park",
        85: "School",
        86: "Stadium",
        87: "Department Store",
        88: "Zoo",
        89: "Convenience Store",
        90: "Live Theater",
        91: "Scales",
        92: "Toll Booth",
        93: "Bridge",
        94: "Building",
        95: "Cemetery",
        96: "Church",
        97: "Civil",
        98: "Crossing",
        99: "Ghost Town",
        100: "Levee",
        101: "Military",
        102: "Oil Field",
        103: "Tunnel",
        104: "Beach",
        105: "Forest",
        106: "Summit",
        107: "Airport",
        108: "Heliport",
        109: "Private Field",
        110: "Soft Field",
        111: "Tall Tower",
        112: "Short Tower",
        113: "Glider Area",
        114: "Ultralight Area",
        115: "Parachute Area",
        116: "Seaplane Base",
        117: "Geocache",
        118: "Geocache Found",
        119: "Contact, Afro",
        120: "Contact, Alien",
        121: "Contact, Ball Cap",
        122: "Contact, Big Ears",
        123: "Contact, Biker",
        124: "Contact, Bug",
        125: "Contact, Cat",
        126: "Contact, Dog",
        127: "Contact, Dreadlocks",
        128: "Contact, Female1",
        129: "Contact, Female2",
        130: "Contact, Female3",
        131: "Contact, Goatee",
        132: "Contact, Kung-Fu",
        133: "Contact, Pig",
        134: "Contact, Pirate",
        135: "Contact, Ranger",
        136: "Contact, Smiley",
        137: "Contact, Spike",
        138: "Contact, Sumo",
        139: "Water Hydrant",
        140: "Flag, Red",
        141: "Flag, Blue",
        142: "Flag, Green",
        143: "Pin, Red",
        144: "Pin, Blue",
        145: "Pin, Green",
        146: "Block, Red",
        147: "Block, Blue",
        148: "Block, Green",
        149: "Bike Trail",
        150: "Fishing Hot Spot Facility",
        151: "Police Station",
        152: "Ski Resort",
        153: "Ice Skating",
        154: "Wrecker",
        155: "Anchor Prohibited",
        156: "Beacon",
        157: "Coast Guard",
        158: "Reef",
        159: "Weed Bed",
        160: "Dropoff",
        161: "Dock",
        162: "Marina",
        163: "Bait and Tackle",
        164: "Stump",
        165: "Circle, Red",
        166: "Circle, Green",
        167: "Circle, Blue",
        168: "Diamond, Blue",
        169: "Oval, Red",
        170: "Oval, Green",
        171: "Oval, Blue",
        172: "Rectangle, Red",
        173: "Rectangle, Green",
        174: "Rectangle, Blue",
        175: "Square, Blue",
        176: "Letter A, Red",
        177: "Letter A, Green",
        178: "Letter A, Blue",
        179: "Letter B, Red",
        180: "Letter B, Green",
        181: "Letter B, Blue",
        182: "Letter C, Red",
        183: "Letter C, Green",
        184: "Letter C, Blue",
        185: "Letter D, Red",
        186: "Letter D, Green",
        187: "Letter D, Blue",
        188: "Number 0, Red",
        189: "Number 0, Green",
        190: "Number 0, Blue",
        191: "Number 1, Red",
        192: "Number 1, Green",
        193: "Number 1, Blue",
        194: "Number 2, Red",
        195: "Number 2, Green",
        196: "Number 2, Blue",
        197: "Number 3, Red",
        198: "Number 3, Green",
        199: "Number 3, Blue",
        200: "Number 4, Red",
        201: "Number 4, Green",
        202: "Number 4, Blue",
        203: "Number 5, Red",
        204: "Number 5, Green",
        205: "Number 5, Blue",
        206: "Number 6, Red",
        207: "Number 6, Green",
        208: "Number 6, Blue",
        209: "Number 7, Red",
        210: "Number 7, Green",
        211: "Number 7, Blue",
        212: "Number 8, Red",
        213: "Number 8, Green",
        214: "Number 8, Blue",
        215: "Number 9, Red",
        216: "Number 9, Green",
        217: "Number 9, Blue",
        218: "Triangle, Blue",
        219: "Triangle, Green",
        220: "Triangle, Red",
    ]
}
